# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]  # Use these Java versions , Current Java LTS & minimum supported by Minecraft
        os: [ ubuntu-latest, windows-latest ] # and run on both Linux and Windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/

      - name: publish
        if: ${{ runner.os != 'Linux' }}
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ZZ5rJltt
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: subset

          curseforge-id: 621693
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: build/libs/*.jar

          name: "Version 1.0.3 for 1.18"
          version: 1.0.3
          version-type: release
          changelog-file: changelog.md

          loaders: |
            forge
          game-versions: |
            1.18
            1.18.1
            1.18.2
          java: |
            17
            18
            19